site_name: Awesome Data Journey
site_author: Anderson Braz de Sousa
site_version: 1.0.0
site_repo: github.com/andersonbraz/andersonbraz.github.io
site_url: https://andersonbraz.github.io
site_description: Experiências e estudos na área de dados e inteligência artificial.

extra_css:
 - assets/stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/semantic-web
  features:
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anderson-braz/
    - icon: fontawesome/brands/github
      link: https://www.github.com/andersonbraz
    - icon: fontawesome/brands/stack-overflow
      link: "https://stackoverflow.com/users/7976603/anderson-braz"
    - icon: fontawesome/brands/hashnode
      link: https://andersonbraz.com
    - icon: fontawesome/brands/telegram
      link: https://telegram.me/braz_anderson
    - icon: material/email
      link: "mailto:contato@andersonbraz.com"
    - icon: fontawesome/brands/verified
      link: "https://www.credly.com/users/andersonbraz"

nav:
  - Sobre: index.md
  - Carreiras:
      - Arquiteto de Dados: carreiras/arquiteto-de-dados.md
      - Engenheiro de Dados: carreiras/engenheiro-de-dados.md
      - Cientista de Dados: carreiras/cientista-de-dados.md
      - Analista de Dados: carreiras/analista-de-dados.md
  - Estudos:
      - Treinamentos: estudos/treinamentos.md
      - Livros: estudos/livros.md
      - Certificações: estudos/certificacoes.md
      - Roadmap 2025: estudos/roadmap.md
  - Metodologias:
      - Agile: metodologias/agile.md
      - CRISP-DM: metodologias/crisp-dm.md
  - Hacks:
      - Git: hacks/git.md
      - Python: hacks/python.md
      - Pandas: hacks/pandas.md
  - Windows:
      - WSL: os-win/wsl.md
      - Spark com WSL: os-win/wsl-spark.md
      - N8N com WSL: os-win/wsl-n8n.md
  - Utilidade Pública:
      - Download: utilidade-publica/download.md
      - Online: utilidade-publica/online.md
      - Meus Favoritos: utilidade-publica/meus-favoritos.md
  - Glossário: glossario.md


copyright: Copyright &copy; 2025 Anderson Braz de Sousa